

CREATE TABLE IF NOT EXISTS equipment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipment_name TEXT NOT NULL,
  category TEXT NOT NULL,
  asset_code TEXT UNIQUE NOT NULL,
  condition TEXT DEFAULT 'Good',
  availability TEXT DEFAULT 'Available',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- TABLE 2: borrow_transactions
-- Stores all borrowing/return transactions
-- ============================================================
CREATE TABLE IF NOT EXISTS borrow_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipment_id BIGINT REFERENCES equipment(id) ON DELETE CASCADE,
  borrower_name TEXT NOT NULL,
  borrower_type TEXT NOT NULL,
  department TEXT NOT NULL,
  date_borrowed DATE DEFAULT CURRENT_DATE,
  due_date DATE NOT NULL,
  date_returned DATE,
  status TEXT DEFAULT 'Borrowed',
  user_id UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- ROW LEVEL SECURITY (RLS)
-- Only authenticated users can access data
-- ============================================================

-- Enable RLS on equipment table
ALTER TABLE equipment ENABLE ROW LEVEL SECURITY;

-- Policy: Authenticated users can SELECT all equipment
CREATE POLICY "Authenticated users can view equipment"
  ON equipment FOR SELECT
  TO authenticated
  USING (true);

-- Policy: Authenticated users can INSERT equipment
CREATE POLICY "Authenticated users can add equipment"
  ON equipment FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Policy: Authenticated users can UPDATE equipment
CREATE POLICY "Authenticated users can update equipment"
  ON equipment FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Policy: Authenticated users can DELETE equipment
CREATE POLICY "Authenticated users can delete equipment"
  ON equipment FOR DELETE
  TO authenticated
  USING (true);

-- Enable RLS on borrow_transactions table
ALTER TABLE borrow_transactions ENABLE ROW LEVEL SECURITY;

-- Policy: Authenticated users can SELECT all transactions
CREATE POLICY "Authenticated users can view transactions"
  ON borrow_transactions FOR SELECT
  TO authenticated
  USING (true);

-- Policy: Authenticated users can INSERT transactions
CREATE POLICY "Authenticated users can add transactions"
  ON borrow_transactions FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Policy: Authenticated users can UPDATE transactions
CREATE POLICY "Authenticated users can update transactions"
  ON borrow_transactions FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Policy: Authenticated users can DELETE transactions
CREATE POLICY "Authenticated users can delete transactions"
  ON borrow_transactions FOR DELETE
  TO authenticated
  USING (true);

-- ============================================================
-- SEED DATA: 10 sample equipment items
-- ============================================================
INSERT INTO equipment (equipment_name, category, asset_code, condition, availability) VALUES
  ('Acer Laptop',        'Laptop',             'LAP-001', 'Good', 'Available'),
  ('Dell Laptop',        'Laptop',             'LAP-002', 'Good', 'Available'),
  ('Epson Projector',    'Projector',          'PROJ-001', 'Good', 'Available'),
  ('Canon DSLR Camera',  'Camera',             'CAM-001', 'Good', 'Available'),
  ('Shure Microphone',   'Microphone',         'MIC-001', 'Good', 'Available'),
  ('TP-Link Router',     'Router',             'RTR-001', 'Fair', 'Available'),
  ('Power Extension Cord','Extension Cord',    'EXT-001', 'Good', 'Available'),
  ('HDMI Cable 3m',      'HDMI Cable',         'HDMI-001', 'Good', 'Available'),
  ('Computer Toolkit',   'Computer Toolkit',   'TKT-001', 'Good', 'Available'),
  ('JBL Portable Speaker','Portable Speaker',  'SPK-001', 'Good', 'Available');

-- ============================================================
-- DONE!
-- Your database tables and seed data are ready.
-- 
-- Next steps:
-- 1. Go to Authentication > Users in Supabase
-- 2. Create a user account for testing
-- 3. Update js/supabase.js with your project URL and anon key
-- ============================================================
